In [1]:
import pandas as pd
from numpy import *
import numpy as np
from sklearn import preprocessing
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import metrics
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
from sklearn import neighbors

In [2]:
#Input as training data
data =pd.read_csv('train dataset.csv')
array = data.values

In [14]:
# Displaying training data
data

,Gender,Age,openness,neuroticism,conscientiousness,agreeableness,extraversion,Personality (Class label)
0,Male,17,7,4,7,3,2,extraverted
1,Male,19,4,5,4,6,6,serious
2,Female,18,7,6,4,5,5,dependable
3,Female,22,5,6,7,4,3,extraverted
4,Female,19,7,4,6,5,4,lively
...,...,...,...,...,...,...,...,...
704,Female,20,4,5,6,6,1,responsible
705,Male,18,6,3,1,5,5,dependable
706,Male,22,5,2,3,6,1,serious
707,Male,19,5,6,5,7,5,extraverted
708,Female,18,5,5,7,6,5,extraverted

In [3]:
#Preprocessing
#Converting Categorical to numerical value
for i in range(len(array)):
	if array[i][0]=="Male":
		array[i][0]=1
	else:
		array[i][0]=0

In [15]:
#Result of conversion
df=pd.DataFrame(array)
df

     0   1  2  3  4  5  6            7
0    1  17  7  4  7  3  2  extraverted
1    1  19  4  5  4  6  6      serious
2    0  18  7  6  4  5  5   dependable
3    0  22  5  6  7  4  3  extraverted
4    0  19  7  4  6  5  4       lively
..  ..  .. .. .. .. .. ..          ...
704  0  20  4  5  6  6  1  responsible
705  1  18  6  3  1  5  5   dependable
706  1  22  5  2  3  6  1      serious
707  1  19  5  6  5  7  5  extraverted
708  0  18  5  5  7  6  5  extraverted

[709 rows x 8 columns]

In [5]:
maindf =df[[0,1,2,3,4,5,6]]
mainarray=maindf.values
print (mainarray)

[[1 17 7 ... 7 3 2]
 [1 19 4 ... 4 6 6]
 [0 18 7 ... 4 5 5]
 ...
 [1 22 5 ... 3 6 1]
 [1 19 5 ... 5 7 5]
 [0 18 5 ... 7 6 5]]

In [6]:
temp=df[7]
train_y =temp.values
# print(train_y)
# print(mainarray)
train_y=temp.values

In [7]:
for i in range(len(train_y)):
	train_y[i] =str(train_y[i])

In [8]:
#Applying Logistic Regression
mul_lr = linear_model.LogisticRegression(multi_class='multinomial', solver='newton-cg',max_iter =1000)
#Training the data
mul_lr.fit(mainarray, train_y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=1000, multi_class='multinomial',
          n_jobs=None, penalty='l2', random_state=None, solver='newton-cg',
          tol=0.0001, verbose=0, warm_start=False)

In [18]:
#Getting test data
testdata =pd.read_csv('test dataset.csv')
test = testdata.values
testdata

,Gender,Age,openness,neuroticism,conscientiousness,agreeableness,extraversion,Personality (class label)
0,Female,20,7,9,9,5,5,dependable
1,Male,17,5,4,5,2,4,serious
2,Female,25,5,5,7,2,4,serious
3,Female,18,6,2,7,4,7,serious
4,Female,19,2,4,7,1,3,responsible
...,...,...,...,...,...,...,...,...
310,Female,19,6,5,6,4,3,extraverted
311,Male,18,2,5,8,3,7,dependable
312,Male,18,7,5,6,2,7,serious
313,Male,23,6,7,5,4,3,extraverted
314,Female,18,5,7,3,5,6,extraverted

In [10]:
#Preprocessing
#Converting Categorical to numerical value
for i in range(len(test)):
	if test[i][0]=="Male":
		test[i][0]=1
	else:
		test[i][0]=0

In [11]:
df1=pd.DataFrame(test)

In [12]:
testdf =df1[[0,1,2,3,4,5,6]]
maintestarray=testdf.values
print(maintestarray)

[[0 20 7 ... 9 5 5]
 [1 17 5 ... 5 2 4]
 [0 25 5 ... 7 2 4]
 ...
 [1 18 7 ... 6 2 7]
 [1 23 6 ... 5 4 3]
 [0 18 5 ... 3 5 6]]

In [30]:
#Predicting Personality
y_pred = mul_lr.predict(maintestarray)
for i in range(len(y_pred)) :
	y_pred[i]=str((y_pred[i]))
	print("Personality for Person No "+str(i)+" is " + y_pred[i])
DF = pd.DataFrame(y_pred,columns=['Predicted Personality'])
DF.index=DF.index+1
DF.index.names = ['Person No']
DF.to_csv("output.csv")

Personality for Person No 0 is dependable
Personality for Person No 1 is serious
Personality for Person No 2 is serious
Personality for Person No 3 is serious
Personality for Person No 4 is responsible
Personality for Person No 5 is serious
Personality for Person No 6 is serious
Personality for Person No 7 is serious
Personality for Person No 8 is serious
Personality for Person No 9 is serious
Personality for Person No 10 is serious
Personality for Person No 11 is responsible
Personality for Person No 12 is responsible
Personality for Person No 13 is serious
Personality for Person No 14 is lively
Personality for Person No 15 is extraverted
Personality for Person No 16 is serious
Personality for Person No 17 is serious
Personality for Person No 18 is serious
Personality for Person No 19 is extraverted
Personality for Person No 20 is serious
Personality for Person No 21 is extraverted
Personality for Person No 22 is serious
Personality for Person No 23 is extraverted
Personality for Person No 24 is serious
Personality for Person No 25 is serious
Personality for Person No 26 is extraverted
Personality for Person No 27 is extraverted
Personality for Person No 28 is serious
Personality for Person No 29 is responsible
Personality for Person No 30 is serious
Personality for Person No 31 is lively
Personality for Person No 32 is extraverted
Personality for Person No 33 is lively
Personality for Person No 34 is serious
Personality for Person No 35 is serious
Personality for Person No 36 is serious
Personality for Person No 37 is serious
Personality for Person No 38 is extraverted
Personality for Person No 39 is serious
Personality for Person No 40 is responsible
Personality for Person No 41 is responsible
Personality for Person No 42 is serious
Personality for Person No 43 is lively
Personality for Person No 44 is serious
Personality for Person No 45 is serious
Personality for Person No 46 is responsible
Personality for Person No 47 is dependable
Personality for Person No 48 is serious
Personality for Person No 49 is extraverted
Personality for Person No 50 is serious
Personality for Person No 51 is serious
Personality for Person No 52 is serious
Personality for Person No 53 is lively
Personality for Person No 54 is extraverted
Personality for Person No 55 is serious
Personality for Person No 56 is extraverted
Personality for Person No 57 is serious
Personality for Person No 58 is serious
Personality for Person No 59 is serious
Personality for Person No 60 is responsible
Personality for Person No 61 is serious
Personality for Person No 62 is dependable
Personality for Person No 63 is serious
Personality for Person No 64 is serious
Personality for Person No 65 is responsible
Personality for Person No 66 is serious
Personality for Person No 67 is serious
Personality for Person No 68 is serious
Personality for Person No 69 is serious
Personality for Person No 70 is serious
Personality for Person No 71 is serious
Personality for Person No 72 is serious
Personality for Person No 73 is serious
Personality for Person No 74 is responsible
Personality for Person No 75 is extraverted
Personality for Person No 76 is serious
Personality for Person No 77 is serious
Personality for Person No 78 is serious
Personality for Person No 79 is extraverted
Personality for Person No 80 is serious
Personality for Person No 81 is serious
Personality for Person No 82 is extraverted
Personality for Person No 83 is extraverted
Personality for Person No 84 is serious
Personality for Person No 85 is lively
Personality for Person No 86 is serious
Personality for Person No 87 is serious
Personality for Person No 88 is serious
Personality for Person No 89 is serious
Personality for Person No 90 is serious
Personality for Person No 91 is responsible
Personality for Person No 92 is serious
Personality for Person No 93 is serious
Personality for Person No 94 is serious
Personality for Person No 95 is serious
Personality for Person No 96 is serious
Personality for Person No 97 is extraverted
Personality for Person No 98 is serious
Personality for Person No 99 is serious
Personality for Person No 100 is extraverted
Personality for Person No 101 is extraverted
Personality for Person No 102 is extraverted
Personality for Person No 103 is extraverted
Personality for Person No 104 is serious
Personality for Person No 105 is serious
Personality for Person No 106 is serious
Personality for Person No 107 is extraverted
Personality for Person No 108 is serious
Personality for Person No 109 is serious
Personality for Person No 110 is serious
Personality for Person No 111 is serious
Personality for Person No 112 is lively
Personality for Person No 113 is serious
Personality for Person No 114 is serious
Personality for Person No 115 is extraverted
Personality for Person No 116 is serious
Personality for Person No 117 is serious
Personality for Person No 118 is serious
Personality for Person No 119 is extraverted
Personality for Person No 120 is lively
Personality for Person No 121 is lively
Personality for Person No 122 is serious
Personality for Person No 123 is serious
Personality for Person No 124 is lively
Personality for Person No 125 is serious
Personality for Person No 126 is serious
Personality for Person No 127 is serious
Personality for Person No 128 is responsible
Personality for Person No 129 is serious
Personality for Person No 130 is serious
Personality for Person No 131 is dependable
Personality for Person No 132 is serious
Personality for Person No 133 is serious
Personality for Person No 134 is dependable
Personality for Person No 135 is serious
Personality for Person No 136 is responsible
Personality for Person No 137 is extraverted
Personality for Person No 138 is serious
Personality for Person No 139 is serious
Personality for Person No 140 is serious
Personality for Person No 141 is serious
Personality for Person No 142 is serious
Personality for Person No 143 is serious
Personality for Person No 144 is serious
Personality for Person No 145 is extraverted
Personality for Person No 146 is serious
Personality for Person No 147 is serious
Personality for Person No 148 is serious
Personality for Person No 149 is extraverted
Personality for Person No 150 is serious
Personality for Person No 151 is lively
Personality for Person No 152 is extraverted
Personality for Person No 153 is extraverted
Personality for Person No 154 is serious
Personality for Person No 155 is responsible
Personality for Person No 156 is extraverted
Personality for Person No 157 is serious
Personality for Person No 158 is extraverted
Personality for Person No 159 is responsible
Personality for Person No 160 is extraverted
Personality for Person No 161 is serious
Personality for Person No 162 is serious
Personality for Person No 163 is serious
Personality for Person No 164 is responsible
Personality for Person No 165 is serious
Personality for Person No 166 is extraverted
Personality for Person No 167 is extraverted
Personality for Person No 168 is extraverted
Personality for Person No 169 is serious
Personality for Person No 170 is serious
Personality for Person No 171 is serious
Personality for Person No 172 is responsible
Personality for Person No 173 is responsible
Personality for Person No 174 is serious
Personality for Person No 175 is serious
Personality for Person No 176 is lively
Personality for Person No 177 is serious
Personality for Person No 178 is serious
Personality for Person No 179 is serious
Personality for Person No 180 is lively
Personality for Person No 181 is serious
Personality for Person No 182 is extraverted
Personality for Person No 183 is extraverted
Personality for Person No 184 is extraverted
Personality for Person No 185 is serious
Personality for Person No 186 is serious
Personality for Person No 187 is extraverted
Personality for Person No 188 is extraverted
Personality for Person No 189 is serious
Personality for Person No 190 is serious
Personality for Person No 191 is extraverted
Personality for Person No 192 is serious
Personality for Person No 193 is lively
Personality for Person No 194 is serious
Personality for Person No 195 is extraverted
Personality for Person No 196 is serious
Personality for Person No 197 is extraverted
Personality for Person No 198 is responsible
Personality for Person No 199 is serious
Personality for Person No 200 is serious
Personality for Person No 201 is serious
Personality for Person No 202 is lively
Personality for Person No 203 is serious
Personality for Person No 204 is serious
Personality for Person No 205 is serious
Personality for Person No 206 is serious
Personality for Person No 207 is extraverted
Personality for Person No 208 is dependable
Personality for Person No 209 is serious
Personality for Person No 210 is extraverted
Personality for Person No 211 is extraverted
Personality for Person No 212 is extraverted
Personality for Person No 213 is extraverted
Personality for Person No 214 is lively
Personality for Person No 215 is serious
Personality for Person No 216 is extraverted
Personality for Person No 217 is dependable
Personality for Person No 218 is serious
Personality for Person No 219 is dependable
Personality for Person No 220 is extraverted
Personality for Person No 221 is extraverted
Personality for Person No 222 is extraverted
Personality for Person No 223 is serious
Personality for Person No 224 is serious
Personality for Person No 225 is extraverted
Personality for Person No 226 is serious
Personality for Person No 227 is extraverted
Personality for Person No 228 is extraverted
Personality for Person No 229 is serious
Personality for Person No 230 is extraverted
Personality for Person No 231 is serious
Personality for Person No 232 is serious
Personality for Person No 233 is extraverted
Personality for Person No 234 is extraverted
Personality for Person No 235 is serious
Personality for Person No 236 is serious
Personality for Person No 237 is extraverted
Personality for Person No 238 is serious
Personality for Person No 239 is serious
Personality for Person No 240 is serious
Personality for Person No 241 is serious
Personality for Person No 242 is extraverted
Personality for Person No 243 is serious
Personality for Person No 244 is serious
Personality for Person No 245 is extraverted
Personality for Person No 246 is serious
Personality for Person No 247 is serious
Personality for Person No 248 is responsible
Personality for Person No 249 is extraverted
Personality for Person No 250 is serious
Personality for Person No 251 is extraverted
Personality for Person No 252 is serious
Personality for Person No 253 is extraverted
Personality for Person No 254 is serious
Personality for Person No 255 is responsible
Personality for Person No 256 is responsible
Personality for Person No 257 is extraverted
Personality for Person No 258 is lively
Personality for Person No 259 is serious
Personality for Person No 260 is responsible
Personality for Person No 261 is responsible
Personality for Person No 262 is lively
Personality for Person No 263 is serious
Personality for Person No 264 is serious
Personality for Person No 265 is extraverted
Personality for Person No 266 is serious
Personality for Person No 267 is serious
Personality for Person No 268 is serious
Personality for Person No 269 is serious
Personality for Person No 270 is extraverted
Personality for Person No 271 is serious
Personality for Person No 272 is extraverted
Personality for Person No 273 is serious
Personality for Person No 274 is responsible
Personality for Person No 275 is responsible
Personality for Person No 276 is extraverted
Personality for Person No 277 is extraverted
Personality for Person No 278 is serious
Personality for Person No 279 is serious
Personality for Person No 280 is responsible
Personality for Person No 281 is extraverted
Personality for Person No 282 is serious
Personality for Person No 283 is extraverted
Personality for Person No 284 is lively
Personality for Person No 285 is dependable
Personality for Person No 286 is serious
Personality for Person No 287 is extraverted
Personality for Person No 288 is extraverted
Personality for Person No 289 is extraverted
Personality for Person No 290 is extraverted
Personality for Person No 291 is extraverted
Personality for Person No 292 is extraverted
Personality for Person No 293 is serious
Personality for Person No 294 is extraverted
Personality for Person No 295 is extraverted
Personality for Person No 296 is extraverted
Personality for Person No 297 is extraverted
Personality for Person No 298 is extraverted
Personality for Person No 299 is extraverted
Personality for Person No 300 is serious
Personality for Person No 301 is serious
Personality for Person No 302 is serious
Personality for Person No 303 is serious
Personality for Person No 304 is serious
Personality for Person No 305 is serious
Personality for Person No 306 is serious
Personality for Person No 307 is serious
Personality for Person No 308 is serious
Personality for Person No 309 is serious
Personality for Person No 310 is extraverted
Personality for Person No 311 is serious
Personality for Person No 312 is serious
Personality for Person No 313 is extraverted
Personality for Person No 314 is extraverted